/**
 * The directory's starting contents.
 *
 * This was the prototype's entire dataset. It is now read by exactly one thing
 * — `db/seed.ts` — and by nothing the app ships. The app reads Postgres.
 *
 * Every business here is invented, and that remains deliberate rather than a
 * placeholder to replace later: a directory that prints an invented headcount,
 * an invented salary band and an invented employee roster under a real
 * company's name is a fabricated record about a real business. The
 * *geography* is real, so every seeded address resolves to a genuine Spokane
 * district at coordinates the map can be trusted with.
 *
 * These rows seed as published and unclaimed. The first person from one of
 * these companies to sign in claims the listing through the same flow
 * everybody else uses — nothing here is privileged except that it ran first.
 */

import type { Company, Job, Person } from "./domain";

export type { Industry } from "./domain";
export { INDUSTRIES } from "./domain";

export const COMPANIES: Company[] = [
  {
    id: "latah-systems",
    name: "Latah Systems",
    hue: 152,
    tagline: "Scheduling for rural hospital networks",
    about:
      "Latah builds the scheduling layer that sits between a critical-access hospital and the specialists it borrows from. Twenty-nine facilities across eastern Washington, north Idaho and western Montana run their referral calendars on it.",
    industry: "Health tech",
    headcount: 124,
    founded: 2014,
    stage: "Series B",
    workplace: "Hybrid",
    district: "downtown",
    address: "601 W Riverside Ave, Suite 1400",
    zip: "99201",
    lng: -117.4243,
    lat: 47.6586,
    website: "latahsystems.com",
    email: "careers@latahsystems.com",
    phone: "(509) 555-0142",
    claimed: true,
  },
  {
    id: "kestrel-aero",
    name: "Kestrel Aero",
    hue: 232,
    tagline: "Composite structures for regional aircraft",
    about:
      "Kestrel lays up and tests composite control surfaces for regional turboprops. The West Plains shop runs two shifts and its own environmental test cell; roughly a third of the floor is apprentices out of the Spokane Community College programme.",
    industry: "Aerospace",
    headcount: 243,
    founded: 2009,
    stage: "Private",
    workplace: "On-site",
    district: "airway-heights",
    address: "11250 W Sunset Hwy",
    zip: "99001",
    lng: -117.5955,
    lat: 47.6421,
    website: "kestrelaero.com",
    email: "jobs@kestrelaero.com",
    phone: "(509) 555-0118",
    claimed: true,
  },
  {
    id: "riverstone-health",
    name: "Riverstone Health",
    hue: 196,
    tagline: "Remote monitoring for chronic care",
    about:
      "Cuffs, scales and glucose meters that report to a care team instead of a drawer. Riverstone's clinical team sits in the University District; the deployment crew spends most of its week in patients' kitchens across the Inland Northwest.",
    industry: "Health tech",
    headcount: 68,
    founded: 2017,
    stage: "Series A",
    workplace: "Hybrid",
    district: "university",
    address: "412 E Spokane Falls Blvd",
    zip: "99202",
    lng: -117.4032,
    lat: 47.6588,
    website: "riverstonehealth.io",
    email: "hello@riverstonehealth.io",
    phone: "(509) 555-0176",
    claimed: true,
  },
  {
    id: "hangman-data",
    name: "Hangman Data",
    hue: 38,
    tagline: "Geospatial analytics for rural utilities",
    about:
      "Hangman reads LiDAR and outage history and tells a co-op which two miles of line to reconductor first. Eleven utilities in Washington, Idaho and Oregon, run out of one floor above a coffee roaster on South Perry.",
    industry: "Data & analytics",
    headcount: 18,
    founded: 2019,
    stage: "Seed",
    workplace: "Hybrid",
    district: "perry",
    address: "1011 S Perry St, Suite 2",
    zip: "99202",
    lng: -117.3904,
    lat: 47.6444,
    website: "hangmandata.com",
    email: "team@hangmandata.com",
    phone: "(509) 555-0193",
    claimed: true,
  },
  {
    id: "coeur-robotics",
    name: "Coeur Robotics",
    hue: 274,
    tagline: "Picking arms for mid-size warehouses",
    about:
      "Coeur sells a picking cell to distributors too small for the systems the national integrators quote. The arm is off the shelf; what Coeur builds is the grasp planner and the two days of setup that let a 40-person warehouse run one.",
    industry: "Robotics",
    headcount: 54,
    founded: 2016,
    stage: "Series A",
    workplace: "On-site",
    district: "valley",
    address: "12615 E Mission Ave",
    zip: "99216",
    lng: -117.2286,
    lat: 47.6714,
    website: "coeurrobotics.com",
    email: "careers@coeurrobotics.com",
    phone: "(509) 555-0155",
    claimed: true,
  },
  {
    id: "manito-bio",
    name: "Manito Bio",
    hue: 128,
    tagline: "Assay automation for small labs",
    about:
      "A benchtop liquid handler and the software to drive it, aimed at labs running a hundred plates a week rather than a hundred thousand. Spun out of a WSU Spokane lab in 2018 and still half its staff.",
    industry: "Health tech",
    headcount: 32,
    founded: 2018,
    stage: "Series A",
    workplace: "On-site",
    district: "south-hill",
    address: "2820 S Grand Blvd",
    zip: "99203",
    lng: -117.4096,
    lat: 47.6298,
    website: "manitobio.com",
    email: "info@manitobio.com",
    phone: "(509) 555-0164",
    claimed: false,
  },
  {
    id: "peaceful-valley",
    name: "Peaceful Valley Software",
    hue: 12,
    tagline: "CI for teams that ship firmware",
    about:
      "Continuous integration that knows what a hardware-in-the-loop rig is. Four people, no outside money, and a customer list that is mostly medical-device teams who cannot use a cloud runner.",
    industry: "Developer tools",
    headcount: 9,
    founded: 2021,
    stage: "Bootstrapped",
    workplace: "Remote-first",
    district: "browne",
    address: "1823 W Pacific Ave",
    zip: "99201",
    lng: -117.4374,
    lat: 47.6524,
    website: "pvsoftware.dev",
    email: "hi@pvsoftware.dev",
    phone: "(509) 555-0107",
    claimed: true,
  },
  {
    id: "garland-interactive",
    name: "Garland Interactive",
    hue: 318,
    tagline: "Couch co-op, still",
    about:
      "Four shipped titles, all of them two-player on one screen. Garland has been profitable since its second game and has never had more than 45 people, which its founders describe as the entire strategy.",
    industry: "Games",
    headcount: 41,
    founded: 2012,
    stage: "Bootstrapped",
    workplace: "Hybrid",
    district: "garland",
    address: "924 W Garland Ave",
    zip: "99205",
    lng: -117.4288,
    lat: 47.6879,
    website: "garlandinteractive.com",
    email: "studio@garlandinteractive.com",
    phone: "(509) 555-0129",
    claimed: true,
  },
  {
    id: "selkirk-security",
    name: "Selkirk Security",
    hue: 214,
    tagline: "Monitoring for industrial control networks",
    about:
      "Selkirk watches the networks that run dams, mills and water districts, where a patch window is measured in years. Largest private employer in Liberty Lake and the reason a third of the region's security engineers live out there.",
    industry: "Cybersecurity",
    headcount: 88,
    founded: 2013,
    stage: "Series B",
    workplace: "Hybrid",
    district: "liberty-lake",
    address: "23505 E Appleway Ave",
    zip: "99019",
    lng: -117.1048,
    lat: 47.6702,
    website: "selkirksec.com",
    email: "careers@selkirksec.com",
    phone: "(509) 555-0188",
    claimed: true,
  },
  {
    id: "palouse-agritech",
    name: "Palouse Agritech",
    hue: 88,
    tagline: "Variable-rate application for dryland wheat",
    about:
      "Prescription maps for growers on ground too dry and too steep for the row-crop tools to make sense on. Founded by two agronomists out of Cheney; most of the field team farms as well.",
    industry: "Agtech",
    headcount: 76,
    founded: 2011,
    stage: "Series B",
    workplace: "Hybrid",
    district: "cheney",
    address: "312 1st St",
    zip: "99004",
    lng: -117.5722,
    lat: 47.4889,
    website: "palouseagritech.com",
    email: "jobs@palouseagritech.com",
    phone: "(509) 555-0134",
    claimed: false,
  },
  {
    id: "monroe-street-labs",
    name: "Monroe Street Labs",
    hue: 258,
    tagline: "Scheduling and invoicing for trades",
    about:
      "One app for the two-van electrical contractor: the calendar, the estimate, the invoice and the follow-up. 2,400 crews across the Northwest, sold almost entirely by word of mouth at supply houses.",
    industry: "Developer tools",
    headcount: 23,
    founded: 2020,
    stage: "Seed",
    workplace: "Remote-first",
    district: "north-monroe",
    address: "2415 N Monroe St",
    zip: "99205",
    lng: -117.4269,
    lat: 47.6746,
    website: "monroestreetlabs.com",
    email: "team@monroestreetlabs.com",
    phone: "(509) 555-0171",
    claimed: true,
  },
  {
    id: "hillyard-freight",
    name: "Hillyard Freight Systems",
    hue: 24,
    tagline: "Less-than-truckload routing, Inland Northwest",
    about:
      "A carrier that writes its own dispatch software, which is unusual at 150 people and is why it turns up in a tech directory at all. The routing team sits above the yard on Market.",
    industry: "Logistics",
    headcount: 152,
    founded: 2008,
    stage: "Employee-owned",
    workplace: "On-site",
    district: "hillyard",
    address: "5024 N Market St",
    zip: "99217",
    lng: -117.3812,
    lat: 47.6998,
    website: "hillyardfreight.com",
    email: "hiring@hillyardfreight.com",
    phone: "(509) 555-0146",
    claimed: false,
  },
  {
    id: "kendall-yards-studio",
    name: "Kendall Yards Studio",
    hue: 342,
    tagline: "Product design for companies without a design team",
    about:
      "Fourteen designers and researchers who work as one team inside a client's product org for six months at a time. Most of the region's Series A companies have had them in the building at some point.",
    industry: "Design studio",
    headcount: 14,
    founded: 2015,
    stage: "Bootstrapped",
    workplace: "Hybrid",
    district: "kendall-yards",
    address: "1335 W Summit Pkwy",
    zip: "99201",
    lng: -117.4352,
    lat: 47.6631,
    website: "kystudio.co",
    email: "studio@kystudio.co",
    phone: "(509) 555-0152",
    claimed: true,
  },
  {
    id: "bigelow-analytics",
    name: "Bigelow Analytics",
    hue: 178,
    tagline: "Lending analytics for credit unions",
    about:
      "Underwriting and portfolio tooling for credit unions between $200M and $3B in assets — institutions with a real lending book and no data team. Forty-seven people, thirty-one of them in Spokane.",
    industry: "Fintech",
    headcount: 47,
    founded: 2016,
    stage: "Series A",
    workplace: "Hybrid",
    district: "downtown",
    address: "108 N Washington St, Suite 300",
    zip: "99201",
    lng: -117.4185,
    lat: 47.6582,
    website: "bigelowanalytics.com",
    email: "careers@bigelowanalytics.com",
    phone: "(509) 555-0161",
    claimed: true,
  },
  {
    id: "millwood-materials",
    name: "Millwood Materials",
    hue: 46,
    tagline: "Precision machining and metrology",
    about:
      "Five-axis work to aerospace tolerances, plus the inspection lab half the region's smaller shops send parts to. Employee-owned since 2016 and the oldest company in this directory by a decade.",
    industry: "Advanced manufacturing",
    headcount: 312,
    founded: 1998,
    stage: "Employee-owned",
    workplace: "On-site",
    district: "millwood",
    address: "9102 E Euclid Ave",
    zip: "99212",
    lng: -117.2841,
    lat: 47.6845,
    website: "millwoodmaterials.com",
    email: "hr@millwoodmaterials.com",
    phone: "(509) 555-0113",
    claimed: false,
  },
  {
    id: "falls-learning",
    name: "Falls Learning",
    hue: 302,
    tagline: "Career and technical education, built with the trades",
    about:
      "Courseware for high-school CTE programmes, written with the unions and shops that hire out of them. Used in 180 districts across five states; the whole company is twenty-nine people above a bike shop.",
    industry: "Education",
    headcount: 29,
    founded: 2019,
    stage: "Seed",
    workplace: "Hybrid",
    district: "downtown",
    address: "159 S Lincoln St, Suite 200",
    zip: "99201",
    lng: -117.4268,
    lat: 47.6551,
    website: "fallslearning.org",
    email: "hello@fallslearning.org",
    phone: "(509) 555-0125",
    claimed: true,
  },
  {
    id: "northtown-commerce",
    name: "Northtown Commerce",
    hue: 8,
    tagline: "Marketplace operations, outsourced",
    about:
      "Runs the Amazon, Walmart and Target storefronts for about sixty mid-size brands — listings, ads, returns and the forecasting behind them. Grew out of a single seller account in 2014.",
    industry: "E-commerce",
    headcount: 61,
    founded: 2014,
    stage: "Private",
    workplace: "On-site",
    district: "shadle",
    address: "2525 W Wellesley Ave",
    zip: "99205",
    lng: -117.4472,
    lat: 47.6919,
    website: "northtowncommerce.com",
    email: "jobs@northtowncommerce.com",
    phone: "(509) 555-0138",
    claimed: false,
  },
  {
    id: "cliff-drive-energy",
    name: "Cliff Drive Energy",
    hue: 164,
    tagline: "Controls for utility-scale storage",
    about:
      "The dispatch software for battery installations between 2 and 40 MWh — deciding, every four seconds, whether a site is charging, discharging or holding. Eleven sites live, mostly in the Columbia Basin.",
    industry: "Cleantech",
    headcount: 38,
    founded: 2020,
    stage: "Series A",
    workplace: "Hybrid",
    district: "south-hill",
    address: "1112 E Cliff Dr",
    zip: "99202",
    lng: -117.4022,
    lat: 47.6428,
    website: "cliffdrive.energy",
    email: "careers@cliffdrive.energy",
    phone: "(509) 555-0182",
    claimed: true,
  },
  {
    id: "basalt-cloud",
    name: "Basalt Cloud",
    hue: 244,
    tagline: "Regional colocation and managed Kubernetes",
    about:
      "Two facilities, both inside the city, for teams that need their data to stay in the state and their latency under five milliseconds. Most customers are health systems and one is a card processor.",
    industry: "Developer tools",
    headcount: 27,
    founded: 2021,
    stage: "Seed",
    workplace: "On-site",
    district: "university",
    address: "850 E Spokane Falls Blvd",
    zip: "99202",
    lng: -117.3966,
    lat: 47.6603,
    website: "basaltcloud.com",
    email: "hello@basaltcloud.com",
    phone: "(509) 555-0199",
    claimed: true,
  },
  {
    id: "five-mile-systems",
    name: "Five Mile Systems",
    hue: 108,
    tagline: "Cold-chain sensors and the network behind them",
    about:
      "Battery-powered temperature loggers that report over LoRa from inside a trailer. Sold to produce shippers and, increasingly, to the pharmacies that discovered in 2021 that nobody was watching the last mile.",
    industry: "Logistics",
    headcount: 35,
    founded: 2017,
    stage: "Series A",
    workplace: "Hybrid",
    district: "north-monroe",
    address: "4104 N Ash St",
    zip: "99205",
    lng: -117.4374,
    lat: 47.6862,
    website: "fivemilesystems.com",
    email: "team@fivemilesystems.com",
    phone: "(509) 555-0177",
    claimed: false,
  },
  {
    id: "post-street-interactive",
    name: "Post Street Interactive",
    hue: 286,
    tagline: "Media buying for regional advertisers",
    about:
      "Places and measures the campaigns for car dealers, hospital systems and tribal enterprises across four states. Built its own attribution stack because none of the ad platforms would tell it what happened in a market of 600,000 people.",
    industry: "Data & analytics",
    headcount: 22,
    founded: 2015,
    stage: "Bootstrapped",
    workplace: "Hybrid",
    district: "downtown",
    address: "9 N Post St, Suite 400",
    zip: "99201",
    lng: -117.4224,
    lat: 47.6578,
    website: "poststreet.io",
    email: "work@poststreet.io",
    phone: "(509) 555-0168",
    claimed: false,
  },
];

export const JOBS: Job[] = [
  {
    id: "latah-be",
    companyId: "latah-systems",
    title: "Senior Backend Engineer, Scheduling",
    discipline: "Engineering",
    level: "Senior",
    employment: "Full-time",
    workplace: "Hybrid",
    payLow: 145000,
    payHigh: 178000,
    posted: 2,
    summary:
      "Own the constraint solver that decides which specialist can be where, and when. It runs against 29 facilities and it cannot be wrong.",
    responsibilities: [
      "Extend the scheduling engine as new facility types come on — infusion, imaging, behavioural health",
      "Cut the referral round trip from its current 40 seconds to something a front-desk clerk will wait for",
      "Carry the on-call pager one week in six, with the whole team",
    ],
    requirements: [
      "Five years or more on a backend that other people's work depends on",
      "Comfortable reasoning about a solver you did not write",
      "Any experience with HL7 or FHIR is useful and none of it is required",
    ],
  },
  {
    id: "latah-design",
    companyId: "latah-systems",
    title: "Product Designer",
    discipline: "Design",
    level: "Mid",
    employment: "Full-time",
    workplace: "Hybrid",
    payLow: 105000,
    payHigh: 128000,
    posted: 9,
    summary:
      "Second designer. The people using this are at a desk in a hospital corridor with a phone ringing, which is the whole brief.",
    responsibilities: [
      "Own the referral and intake flows end to end, research through spec",
      "Sit in on clinic visits — everyone here does, about a day a month",
      "Keep the component library honest as two more product lines land on it",
    ],
    requirements: [
      "A portfolio with at least one dense, unglamorous internal tool in it",
      "You write the copy in your own mockups",
      "Willing to be in the Riverside office two days a week",
    ],
  },
  {
    id: "latah-support",
    companyId: "latah-systems",
    title: "Implementation Specialist",
    discipline: "Support",
    level: "Mid",
    employment: "Full-time",
    workplace: "Hybrid",
    payLow: 68000,
    payHigh: 82000,
    posted: 21,
    summary:
      "Take a hospital from signed to live in six weeks, mostly over the phone and occasionally in a car to Colville.",
    responsibilities: [
      "Run the configuration workshops and the data migration",
      "Train front-desk staff, who did not ask for a new system",
      "Feed the pattern back to product when the same workaround shows up twice",
    ],
    requirements: [
      "You have worked in or next to a clinic",
      "Patient with software and with people, in that order",
      "Valid driver's licence — about six overnight trips a year",
    ],
  },
  {
    id: "kestrel-tech",
    companyId: "kestrel-aero",
    title: "Composite Layup Technician",
    discipline: "Operations",
    level: "Mid",
    employment: "Full-time",
    workplace: "On-site",
    payLow: 27,
    payHigh: 36,
    hourly: true,
    posted: 4,
    summary:
      "Second shift on the layup floor. Hand layup and vacuum bagging to print, on flight hardware.",
    responsibilities: [
      "Lay up, bag and cure control-surface assemblies to the travelling work order",
      "Own first-article inspection on your own parts",
      "Keep the shop's FOD discipline, which is not negotiable",
    ],
    requirements: [
      "Two years of composite work, or the SCC composites certificate",
      "Able to read a drawing and a ply table",
      "Second shift: 2:30pm to 11pm, ten-percent differential",
    ],
  },
  {
    id: "kestrel-apprentice",
    companyId: "kestrel-aero",
    title: "Manufacturing Apprentice",
    discipline: "Operations",
    level: "Junior",
    employment: "Apprentice",
    workplace: "On-site",
    payLow: 22,
    payHigh: 22,
    hourly: true,
    posted: 16,
    summary:
      "Two-year paid apprenticeship, rotating through layup, bonding, NDT and the test cell. Six places a year.",
    responsibilities: [
      "Six months on each of four stations, with a journey-level mentor on each",
      "Classroom day every other Friday, paid, at the SCC campus",
      "Finish with an aerospace manufacturing certificate and a job offer",
    ],
    requirements: [
      "High school diploma or GED",
      "No experience at all — that is the point of the programme",
      "Eighteen or older, and able to lift 40lb repeatedly",
    ],
  },
  {
    id: "kestrel-quality",
    companyId: "kestrel-aero",
    title: "Quality Engineer",
    discipline: "Engineering",
    level: "Senior",
    employment: "Full-time",
    workplace: "On-site",
    payLow: 98000,
    payHigh: 122000,
    posted: 33,
    summary:
      "Own AS9100 for the West Plains site, and the corrective actions that come with it.",
    responsibilities: [
      "Run internal audit and customer audit prep",
      "Root-cause the escapes, and mean it — not five whys on a form",
      "Sit with the layup leads weekly rather than emailing them findings",
    ],
    requirements: [
      "AS9100 or equivalent in a regulated manufacturing setting",
      "CQE is welcome and not required",
      "On-site, first shift",
    ],
  },
  {
    id: "riverstone-mobile",
    companyId: "riverstone-health",
    title: "Mobile Engineer (iOS)",
    discipline: "Engineering",
    level: "Mid",
    employment: "Full-time",
    workplace: "Hybrid",
    payLow: 118000,
    payHigh: 142000,
    posted: 1,
    summary:
      "The patient app, used mostly by people over 70 with a device they did not choose. Accessibility here is the product, not a checklist.",
    responsibilities: [
      "Own the iOS app — Swift, no cross-platform layer",
      "Pair Bluetooth devices reliably in a house with bad wifi and worse patience",
      "Ship against real VoiceOver and Dynamic Type testing every release",
    ],
    requirements: [
      "Three years of shipped iOS",
      "You have fixed an accessibility bug that nobody filed",
      "Core Bluetooth experience earns you a lot of goodwill here",
    ],
  },
  {
    id: "riverstone-clinical",
    companyId: "riverstone-health",
    title: "Clinical Operations Lead",
    discipline: "Operations",
    level: "Lead",
    employment: "Full-time",
    workplace: "Hybrid",
    payLow: 96000,
    payHigh: 118000,
    posted: 12,
    summary:
      "Run the nursing team that reads what the devices send and decides whether anybody needs to be called.",
    responsibilities: [
      "Manage six remote-monitoring nurses across two time zones",
      "Own the escalation protocols, with the medical director",
      "Set the caseload numbers and defend them when sales wants them raised",
    ],
    requirements: [
      "RN, active Washington licence",
      "You have managed clinical staff before, not just been one",
      "Comfortable saying no to a roadmap",
    ],
  },
  {
    id: "hangman-geo",
    companyId: "hangman-data",
    title: "Geospatial Data Engineer",
    discipline: "Data",
    level: "Senior",
    employment: "Full-time",
    workplace: "Hybrid",
    payLow: 132000,
    payHigh: 158000,
    posted: 6,
    summary:
      "Turn 400GB of LiDAR and forty years of paper outage logs into something a line crew can act on.",
    responsibilities: [
      "Own the ingest pipeline — point clouds in, vegetation encroachment out",
      "Keep the whole thing runnable on one machine, which is a deliberate constraint",
      "Go out with a crew twice a year and watch what they actually do with it",
    ],
    requirements: [
      "PostGIS, GDAL and a healthy suspicion of coordinate reference systems",
      "Python for the pipeline; the API is Go and you can learn it here",
      "Utility or forestry data experience is a real advantage",
    ],
  },
  {
    id: "hangman-founding-designer",
    companyId: "hangman-data",
    title: "Founding Designer",
    discipline: "Design",
    level: "Senior",
    employment: "Full-time",
    workplace: "Hybrid",
    payLow: 122000,
    payHigh: 145000,
    posted: 28,
    summary:
      "First designer at eighteen people. Everything on screen is currently a map with too much on it.",
    responsibilities: [
      "Design the analyst-facing product, which is maps, tables and one very hard prioritisation screen",
      "Set up whatever design system a company this size should have, which is not much",
      "Do the sales deck too — everyone here does something outside their title",
    ],
    requirements: [
      "You have designed data-dense tooling and have opinions about legends",
      "Comfortable being the only designer",
      "Cartography experience is a bonus nobody expects",
    ],
  },
  {
    id: "coeur-perception",
    companyId: "coeur-robotics",
    title: "Perception Engineer",
    discipline: "Engineering",
    level: "Staff",
    employment: "Full-time",
    workplace: "On-site",
    payLow: 158000,
    payHigh: 192000,
    posted: 3,
    summary:
      "Grasp planning against unlabelled, unlit, badly-stacked boxes in a warehouse that will not be reorganised for you.",
    responsibilities: [
      "Own segmentation and pose estimation on the picking cell",
      "Get cycle time under nine seconds without dropping the reliability figure",
      "Work on the floor next to the cell, because the failures do not reproduce at a desk",
    ],
    requirements: [
      "Shipped perception on a robot that customers use",
      "Deep with point clouds, ROS 2 and C++",
      "On-site in the Valley — this role cannot be remote and we will not pretend otherwise",
    ],
  },
  {
    id: "coeur-field",
    companyId: "coeur-robotics",
    title: "Field Service Engineer",
    discipline: "Support",
    level: "Mid",
    employment: "Full-time",
    workplace: "On-site",
    payLow: 78000,
    payHigh: 96000,
    posted: 18,
    summary:
      "Install, commission and rescue picking cells across the Northwest. About half your weeks have a flight in them.",
    responsibilities: [
      "Two-day installs, start to signed acceptance",
      "Diagnose over the phone first, fly second",
      "Write up every fix so the next person does not rediscover it",
    ],
    requirements: [
      "Industrial automation or robotics service background",
      "Mechanical and electrical both, and calm in a live warehouse",
      "50% travel, mostly Washington, Oregon and Idaho",
    ],
  },
  {
    id: "coeur-intern",
    companyId: "coeur-robotics",
    title: "Robotics Intern (Summer)",
    discipline: "Engineering",
    level: "Junior",
    employment: "Internship",
    workplace: "On-site",
    payLow: 26,
    payHigh: 30,
    hourly: true,
    posted: 40,
    summary:
      "Twelve weeks on the test cell. Two of the last four interns are now on staff.",
    responsibilities: [
      "Own one scoped project on the gripper test rig, start to demo",
      "Sit in on customer calls — you will hear what actually breaks",
      "Present at the all-hands in week eleven",
    ],
    requirements: [
      "Currently enrolled, any year, any of ME, EE or CS",
      "You have built something physical that worked once",
      "Available June through August, on-site",
    ],
  },
  {
    id: "peaceful-valley-eng",
    companyId: "peaceful-valley",
    title: "Systems Engineer",
    discipline: "Engineering",
    level: "Senior",
    employment: "Full-time",
    workplace: "Remote-first",
    payLow: 138000,
    payHigh: 165000,
    posted: 7,
    summary:
      "Fifth person. The runner agent that drives hardware-in-the-loop rigs is the whole company and it is currently one very brave Rust binary.",
    responsibilities: [
      "Own the runner agent — scheduling, isolation, artefact capture",
      "Make a rig that hangs mid-test recoverable without a human walking to it",
      "Answer support yourself, one week in five, like everyone",
    ],
    requirements: [
      "Rust or C++ at a systems level, and Linux to the same depth",
      "You have been on a firmware team, or close enough to know why CI is hard there",
      "Remote anywhere in US Pacific or Mountain time",
    ],
  },
  {
    id: "garland-gameplay",
    companyId: "garland-interactive",
    title: "Gameplay Programmer",
    discipline: "Engineering",
    level: "Mid",
    employment: "Full-time",
    workplace: "Hybrid",
    payLow: 108000,
    payHigh: 132000,
    posted: 11,
    summary:
      "Unannounced fourth title. Two-player split-screen, which is a constraint that makes every system harder and the game better.",
    responsibilities: [
      "Build and tune the moment-to-moment systems — movement, traversal, the co-op verbs",
      "Own performance on the lowest console we ship to, from the start rather than at the end",
      "Playtest on the couch every Thursday, with everyone",
    ],
    requirements: [
      "One shipped title, any size, any platform",
      "C++ and Unreal, or the appetite to learn Unreal quickly",
      "You care about feel and can say why something feels wrong",
    ],
  },
  {
    id: "garland-tech-art",
    companyId: "garland-interactive",
    title: "Technical Artist",
    discipline: "Design",
    level: "Senior",
    employment: "Full-time",
    workplace: "Hybrid",
    payLow: 115000,
    payHigh: 140000,
    posted: 25,
    summary:
      "Sit between the art team and the frame budget and keep both of them honest.",
    responsibilities: [
      "Own shaders, lighting setup and the art pipeline into Unreal",
      "Profile relentlessly — split-screen doubles everything",
      "Build the tools the artists ask for twice",
    ],
    requirements: [
      "Shipped tech art on console",
      "HLSL, Blueprint, Python for tooling",
      "Hybrid: three days a week on Garland",
    ],
  },
  {
    id: "selkirk-detection",
    companyId: "selkirk-security",
    title: "Detection Engineer, ICS",
    discipline: "Engineering",
    level: "Senior",
    employment: "Full-time",
    workplace: "Hybrid",
    payLow: 142000,
    payHigh: 172000,
    posted: 5,
    summary:
      "Write the detections that fire on a Modbus network where every anomaly is also a Tuesday.",
    responsibilities: [
      "Own the detection library for the protocols our customers actually run",
      "Cut false positives — an alert nobody believes is worse than no alert",
      "Support incident response when something real happens, whatever hour that is",
    ],
    requirements: [
      "OT or ICS security experience, not just IT",
      "Fluent in at least one industrial protocol at the packet level",
      "US person status required by several of our customers",
    ],
  },
  {
    id: "selkirk-analyst",
    companyId: "selkirk-security",
    title: "SOC Analyst (Tier 2)",
    discipline: "Operations",
    level: "Mid",
    employment: "Full-time",
    workplace: "On-site",
    payLow: 84000,
    payHigh: 102000,
    posted: 14,
    summary:
      "Second-tier triage on a floor that watches dams and water districts. Four-on, four-off, twelve-hour shifts.",
    responsibilities: [
      "Own escalated alerts end to end and write the customer-facing findings",
      "Improve the playbooks you find wanting, rather than following them into a wall",
      "Hand off properly — a bad handoff is the only way this team loses",
    ],
    requirements: [
      "Two years in a SOC, any sector",
      "You can write a clear paragraph under pressure",
      "On-site in Liberty Lake; shift differential for nights",
    ],
  },
  {
    id: "selkirk-pm",
    companyId: "selkirk-security",
    title: "Product Manager, Platform",
    discipline: "Product",
    level: "Senior",
    employment: "Full-time",
    workplace: "Hybrid",
    payLow: 138000,
    payHigh: 162000,
    posted: 36,
    summary:
      "Own the half of the product the analysts touch all day, in a market where the buyer and the user are never the same person.",
    responsibilities: [
      "Set the roadmap for the analyst console and the detection content pipeline",
      "Spend real time in customer SOCs, on their shifts",
      "Say no to the feature the last RFP asked for",
    ],
    requirements: [
      "Product experience in security, infrastructure or something equally unforgiving",
      "You have shipped for expert users and resisted simplifying them",
      "Hybrid, two days in Liberty Lake",
    ],
  },
  {
    id: "palouse-agronomy",
    companyId: "palouse-agritech",
    title: "Field Agronomist",
    discipline: "Operations",
    level: "Mid",
    employment: "Full-time",
    workplace: "On-site",
    payLow: 72000,
    payHigh: 89000,
    posted: 8,
    summary:
      "Cover the Palouse from Colfax to Rosalia. Half the job is soil, half is convincing a fourth-generation grower to try one field.",
    responsibilities: [
      "Build prescriptions with growers on their own ground",
      "Run the trial plots and report what they actually showed",
      "Bring the field back to product — twice a year, in person, in the Cheney office",
    ],
    requirements: [
      "Agronomy degree or equivalent time in the field",
      "CCA certification, or willingness to get it in your first year",
      "You are on a farm most days; the truck is provided",
    ],
  },
  {
    id: "palouse-data",
    companyId: "palouse-agritech",
    title: "Data Scientist, Yield Models",
    discipline: "Data",
    level: "Senior",
    employment: "Full-time",
    workplace: "Hybrid",
    payLow: 136000,
    payHigh: 160000,
    posted: 30,
    summary:
      "Model dryland yield where the dominant variable is rain that either came in May or did not.",
    responsibilities: [
      "Own the yield and response models end to end, including the part where they are wrong",
      "Quantify uncertainty in a way an agronomist will read",
      "Ship models that run on a laptop in a field with no signal",
    ],
    requirements: [
      "Strong applied statistics — this is not a deep-learning job",
      "Python, and the discipline to keep a model simple",
      "Interest in agriculture matters more than experience in it",
    ],
  },
  {
    id: "monroe-full-stack",
    companyId: "monroe-street-labs",
    title: "Full-Stack Engineer",
    discipline: "Engineering",
    level: "Mid",
    employment: "Full-time",
    workplace: "Remote-first",
    payLow: 112000,
    payHigh: 136000,
    posted: 10,
    summary:
      "Seventh engineer. The people using this are on a roof with one bar of signal and a glove on.",
    responsibilities: [
      "Ship whole features — schema through the screen",
      "Make the offline path genuinely work, not degrade gracefully",
      "Take support escalations one week in six",
    ],
    requirements: [
      "TypeScript across the stack; Postgres underneath",
      "You have built something that has to work without a network",
      "Remote in US Pacific or Mountain; quarterly week in Spokane, paid",
    ],
  },
  {
    id: "monroe-support",
    companyId: "monroe-street-labs",
    title: "Customer Support Specialist",
    discipline: "Support",
    level: "Junior",
    employment: "Full-time",
    workplace: "Remote-first",
    payLow: 52000,
    payHigh: 62000,
    posted: 22,
    summary:
      "First line for 2,400 contractors, most of whom call rather than email and are usually in a van.",
    responsibilities: [
      "Answer phone and email, resolve most of it yourself",
      "Log the pattern, not just the ticket",
      "Write the help article the third time a question comes up",
    ],
    requirements: [
      "You have done support for people who are not at a computer",
      "Clear writer, patient talker",
      "Remote, Pacific time hours",
    ],
  },
  {
    id: "bigelow-data",
    companyId: "bigelow-analytics",
    title: "Analytics Engineer",
    discipline: "Data",
    level: "Mid",
    employment: "Full-time",
    workplace: "Hybrid",
    payLow: 118000,
    payHigh: 140000,
    posted: 13,
    summary:
      "Build the models credit unions make lending decisions on, in an industry where the source data arrives as a fixed-width file.",
    responsibilities: [
      "Own the transformation layer — dbt, Postgres, a great deal of care",
      "Reconcile against the core system every month and explain every variance",
      "Make the lineage legible to an auditor who is not technical",
    ],
    requirements: [
      "SQL to a serious depth; dbt in production",
      "You have worked somewhere a wrong number has consequences",
      "Financial services experience helps and is not required",
    ],
  },
  {
    id: "bigelow-sales",
    companyId: "bigelow-analytics",
    title: "Account Executive, Credit Unions",
    discipline: "Sales",
    level: "Senior",
    employment: "Full-time",
    workplace: "Hybrid",
    payLow: 105000,
    payHigh: 125000,
    posted: 19,
    summary:
      "Twelve to eighteen month cycles, boards that meet monthly, and buyers who will know you for a decade.",
    responsibilities: [
      "Own the western region — about 400 institutions in range",
      "Present to boards and credit committees, not just to a CTO",
      "Bring the real objection back to product rather than the polite one",
    ],
    requirements: [
      "You have sold into regulated financial institutions",
      "Comfortable with a long cycle and a small pipeline",
      "Roughly 30% travel; base and commission split about evenly",
    ],
  },
  {
    id: "falls-curriculum",
    companyId: "falls-learning",
    title: "Curriculum Designer, Trades",
    discipline: "Design",
    level: "Mid",
    employment: "Full-time",
    workplace: "Hybrid",
    payLow: 74000,
    payHigh: 92000,
    posted: 15,
    summary:
      "Write the welding and electrical modules with the people who hire out of them, and with the teachers who have to run them on a Tuesday.",
    responsibilities: [
      "Build course units against the state CTE frameworks",
      "Work with journeymen and shop teachers as your primary sources",
      "Watch a class run your unit at least once per module",
    ],
    requirements: [
      "Curriculum or instructional design experience, ideally CTE",
      "A trade background is worth more here than a degree",
      "Some travel to district partners across the state",
    ],
  },
  {
    id: "falls-eng",
    companyId: "falls-learning",
    title: "Frontend Engineer",
    discipline: "Engineering",
    level: "Junior",
    employment: "Full-time",
    workplace: "Hybrid",
    payLow: 84000,
    payHigh: 102000,
    posted: 31,
    summary:
      "The student-facing app runs on district Chromebooks from 2019. That is the performance budget and it is not moving.",
    responsibilities: [
      "Build the student and teacher screens in React and TypeScript",
      "Hold the line on bundle size and time to interactive",
      "Test on the actual hardware, which is in a cupboard here",
    ],
    requirements: [
      "You can build a solid, accessible interface; a year or two of doing it counts",
      "Curious about performance rather than frightened of it",
      "Hybrid, three days downtown",
    ],
  },
  {
    id: "cliff-controls",
    companyId: "cliff-drive-energy",
    title: "Controls Engineer",
    discipline: "Engineering",
    level: "Senior",
    employment: "Full-time",
    workplace: "Hybrid",
    payLow: 144000,
    payHigh: 174000,
    posted: 5,
    summary:
      "The four-second loop that decides whether 40MWh charges, discharges or holds. It has never missed a dispatch and that is the bar.",
    responsibilities: [
      "Own the site controller — real-time, safety-critical, no excuses",
      "Model the market signals the dispatch decision runs against",
      "Commission new sites in the Basin, a few weeks a year",
    ],
    requirements: [
      "Real-time control systems in production",
      "Power systems background, or a strong appetite to acquire one fast",
      "C and Python; IEC 61850 is a plus",
    ],
  },
  {
    id: "cliff-ops",
    companyId: "cliff-drive-energy",
    title: "Operations Analyst",
    discipline: "Operations",
    level: "Junior",
    employment: "Full-time",
    workplace: "Hybrid",
    payLow: 68000,
    payHigh: 84000,
    posted: 27,
    summary:
      "Watch eleven sites, settle the market positions and find the five percent of dispatches that left money on the table.",
    responsibilities: [
      "Daily settlement and variance analysis against the market",
      "Own the operations dashboard and what it chooses to show",
      "Escalate anything that looks like a controller getting it wrong",
    ],
    requirements: [
      "Strong with a spreadsheet and honest about its limits",
      "Interest in power markets; we will teach the rest",
      "Hybrid, two days on the South Hill",
    ],
  },
  {
    id: "basalt-sre",
    companyId: "basalt-cloud",
    title: "Site Reliability Engineer",
    discipline: "Engineering",
    level: "Senior",
    employment: "Full-time",
    workplace: "On-site",
    payLow: 134000,
    payHigh: 160000,
    posted: 17,
    summary:
      "Two facilities, one card processor and several health systems. Uptime here is somebody's chart being available.",
    responsibilities: [
      "Own the managed Kubernetes control plane across both sites",
      "Run the failover drills for real, quarterly",
      "Be in the building — the hardware is here and so is the job",
    ],
    requirements: [
      "Kubernetes in anger, not in a tutorial",
      "Networking to the BGP level",
      "On-site in the University District; one-week-in-four on-call",
    ],
  },
  {
    id: "five-mile-firmware",
    companyId: "five-mile-systems",
    title: "Embedded Firmware Engineer",
    discipline: "Engineering",
    level: "Mid",
    employment: "Full-time",
    workplace: "Hybrid",
    payLow: 118000,
    payHigh: 142000,
    posted: 20,
    summary:
      "A logger that has to run three years on one cell, inside a steel trailer, and never lie about a temperature.",
    responsibilities: [
      "Own the sensor firmware — C, bare metal, every microamp accounted for",
      "Work the LoRa link budget with the hardware team",
      "Be the person who trusts the field data over the bench data",
    ],
    requirements: [
      "Embedded C on a constrained MCU, shipped",
      "You have chased a power draw down with a scope",
      "LoRaWAN experience is a genuine head start",
    ],
  },
  {
    id: "post-street-analyst",
    companyId: "post-street-interactive",
    title: "Marketing Analyst",
    discipline: "Data",
    level: "Junior",
    employment: "Full-time",
    workplace: "Hybrid",
    payLow: 62000,
    payHigh: 76000,
    posted: 24,
    summary:
      "Work out what actually happened in a market of 600,000 people, where every platform's own report says it was them.",
    responsibilities: [
      "Own reporting for about a dozen regional accounts",
      "Keep the attribution model honest when a client does not like the answer",
      "Present the monthly read yourself",
    ],
    requirements: [
      "Comfortable in SQL and a spreadsheet",
      "You can explain a number to someone who would rather it were different",
      "Hybrid, downtown",
    ],
  },
  {
    id: "ky-researcher",
    companyId: "kendall-yards-studio",
    title: "Design Researcher",
    discipline: "Design",
    level: "Mid",
    employment: "Contract",
    workplace: "Hybrid",
    payLow: 85,
    payHigh: 110,
    hourly: true,
    posted: 34,
    summary:
      "Six-month engagement embedded with a client health-tech team. Extendable, and two of the last three have gone permanent with the studio.",
    responsibilities: [
      "Run generative and evaluative research inside the client's own org",
      "Teach their PMs to run the evaluative half themselves by the end",
      "Bring what you learn back to the studio's practice",
    ],
    requirements: [
      "You have run research in a regulated domain",
      "Comfortable being the only researcher in a client's building",
      "Contract, 30 to 40 hours a week, hybrid in Kendall Yards",
    ],
  },
];

export const PEOPLE: Person[] = [
  {
    id: "maya-okonkwo",
    name: "Maya Okonkwo",
    hue: 152,
    role: "Staff Backend Engineer",
    companyId: "latah-systems",
    district: "downtown",
    openTo: false,
    skills: ["Go", "Postgres", "Distributed systems", "HL7"],
    bio: "Eight years on scheduling and constraint systems. Wrote most of the solver Latah runs on and would rather talk about the parts of it that are wrong.",
    years: 11,
  },
  {
    id: "daniel-reyes",
    name: "Daniel Reyes",
    hue: 342,
    role: "Product Designer",
    companyId: null,
    district: "perry",
    openTo: true,
    skills: ["Product design", "Design systems", "Research", "Figma"],
    bio: "Six years designing internal tools for people who did not choose the software. Left an agency in March and looking for a product team small enough to sit next to.",
    years: 6,
  },
  {
    id: "priya-raman",
    name: "Priya Raman",
    hue: 196,
    role: "Clinical Operations Lead",
    companyId: "riverstone-health",
    district: "university",
    openTo: false,
    skills: ["RN", "Remote monitoring", "Care protocols", "Team management"],
    bio: "Nurse first, manager second. Runs the monitoring floor and sets the caseload numbers the rest of the company plans against.",
    years: 14,
  },
  {
    id: "tom-whitehorse",
    name: "Tom Whitehorse",
    hue: 38,
    role: "Geospatial Engineer",
    companyId: "hangman-data",
    district: "perry",
    openTo: false,
    skills: ["PostGIS", "Python", "LiDAR", "GDAL"],
    bio: "Came out of forestry rather than software, which is why Hangman's pipeline assumes the data is wrong until proven otherwise.",
    years: 9,
  },
  {
    id: "sarah-kellerman",
    name: "Sarah Kellerman",
    hue: 274,
    role: "Perception Engineer",
    companyId: "coeur-robotics",
    district: "valley",
    openTo: false,
    skills: ["C++", "ROS 2", "Point clouds", "Grasp planning"],
    bio: "Spends most of her week standing next to a picking cell. Firmly of the view that perception bugs do not reproduce at a desk.",
    years: 7,
  },
  {
    id: "andre-boucher",
    name: "André Boucher",
    hue: 12,
    role: "Systems Engineer",
    companyId: "peaceful-valley",
    district: "browne",
    openTo: false,
    skills: ["Rust", "Linux", "CI/CD", "Embedded"],
    bio: "Fourth person at Peaceful Valley. Previously eleven years on medical-device firmware, which is where the idea for the company came from.",
    years: 15,
  },
  {
    id: "jess-nakamura",
    name: "Jess Nakamura",
    hue: 318,
    role: "Technical Artist",
    companyId: "garland-interactive",
    district: "garland",
    openTo: true,
    skills: ["HLSL", "Unreal", "Lighting", "Pipeline tooling"],
    bio: "Three shipped console titles. Happy at Garland and open to hearing about something with a bigger frame budget and a smaller commute.",
    years: 10,
  },
  {
    id: "marcus-ellery",
    name: "Marcus Ellery",
    hue: 214,
    role: "Detection Engineer",
    companyId: "selkirk-security",
    district: "liberty-lake",
    openTo: false,
    skills: ["ICS/OT", "Modbus", "Detection engineering", "Incident response"],
    bio: "Came to security from eight years as a plant controls technician, which turns out to be the shortest path to being good at this.",
    years: 12,
  },
  {
    id: "hana-lindqvist",
    name: "Hana Lindqvist",
    hue: 88,
    role: "Data Scientist",
    companyId: "palouse-agritech",
    district: "cheney",
    openTo: false,
    skills: ["Applied statistics", "Python", "Spatial models", "Agronomy"],
    bio: "Works on yield models where the dominant variable is May rainfall. Grew up on a wheat farm outside Ritzville and says that is the useful qualification.",
    years: 8,
  },
  {
    id: "kyle-tran",
    name: "Kyle Tran",
    hue: 258,
    role: "Full-Stack Engineer",
    companyId: "monroe-street-labs",
    district: "north-monroe",
    openTo: false,
    skills: ["TypeScript", "Postgres", "Offline-first", "React"],
    bio: "Builds for people on roofs with one bar of signal. Has strong and specific opinions about sync conflict resolution.",
    years: 6,
  },
  {
    id: "rebecca-adeyemi",
    name: "Rebecca Adeyemi",
    hue: 178,
    role: "Analytics Engineer",
    companyId: "bigelow-analytics",
    district: "downtown",
    openTo: true,
    skills: ["SQL", "dbt", "Data modelling", "Financial services"],
    bio: "Four years turning credit-union core exports into something an examiner will accept. Looking for a team where the data is less hostile.",
    years: 9,
  },
  {
    id: "owen-brightwater",
    name: "Owen Brightwater",
    hue: 302,
    role: "Curriculum Designer",
    companyId: "falls-learning",
    district: "downtown",
    openTo: false,
    skills: ["Instructional design", "CTE", "Welding", "Assessment"],
    bio: "Fifteen years as a welder, six as a shop teacher, now writes the modules the shop teachers have to run. Knows exactly which ones will not survive a Tuesday.",
    years: 21,
  },
  {
    id: "lucia-ferreira",
    name: "Lucia Ferreira",
    hue: 164,
    role: "Controls Engineer",
    companyId: "cliff-drive-energy",
    district: "south-hill",
    openTo: false,
    skills: ["Real-time control", "Power systems", "C", "IEC 61850"],
    bio: "Owns the loop that decides what 40MWh does next. Previously six years commissioning substations, which is where the paranoia comes from.",
    years: 13,
  },
  {
    id: "nate-osborne",
    name: "Nate Osborne",
    hue: 244,
    role: "Site Reliability Engineer",
    companyId: "basalt-cloud",
    district: "university",
    openTo: false,
    skills: ["Kubernetes", "BGP", "Terraform", "On-call"],
    bio: "Runs the control plane across both Basalt facilities. Has opinions about failover drills that are only ever rehearsed on paper.",
    years: 10,
  },
  {
    id: "amara-diallo",
    name: "Amara Diallo",
    hue: 108,
    role: "Embedded Firmware Engineer",
    companyId: "five-mile-systems",
    district: "north-monroe",
    openTo: true,
    skills: ["Embedded C", "LoRaWAN", "Low power", "RF"],
    bio: "Gets three years out of one cell inside a steel trailer. Open to embedded work anywhere in the region, ideally still hardware that goes outside.",
    years: 8,
  },
  {
    id: "grant-molinaro",
    name: "Grant Molinaro",
    hue: 46,
    role: "Quality Engineer",
    companyId: "millwood-materials",
    district: "millwood",
    openTo: false,
    skills: ["AS9100", "Metrology", "GD&T", "Root cause"],
    bio: "Runs the inspection lab half the region's shops send parts to. Will tell you your tolerance stack is the real problem, and will be right.",
    years: 19,
  },
  {
    id: "elena-vasquez",
    name: "Elena Vasquez",
    hue: 232,
    role: "Design Researcher",
    companyId: "kendall-yards-studio",
    district: "kendall-yards",
    openTo: false,
    skills: ["Research", "Regulated domains", "Workshops", "Synthesis"],
    bio: "Embeds with client teams for six months at a time and leaves them running their own evaluative research. That handover is the job.",
    years: 11,
  },
  {
    id: "wesley-kim",
    name: "Wesley Kim",
    hue: 24,
    role: "Software Engineer",
    companyId: null,
    district: "hillyard",
    openTo: true,
    skills: ["Python", "Go", "Routing", "Logistics"],
    bio: "Wrote dispatch software at a carrier for five years. Finishing a contract in June and looking for something in the region that is not a rewrite of the same system.",
    years: 7,
  },
];

